export const SET_DESIGN_TEMPLATE = 'SET_DESIGN_TEMPLATE';
export const FETCH_DESIGN_TEMPLATE_FAIL = 'FETCH_DESIGN_TEMPLATE_FAIL';
export const SET_FOCUS = 'SET_FOCUS';
export const SET_CANVAS = 'SET_CANVAS';
export const SET_FOUCS_COLOR = "SET_FOUCS_COLOR";

export const SET_DISPLAY_IMAGE = "SET_DISPLAY_IMAGE";